name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Verificação de estilo (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalando dependências
        run: npm ci

      - name: Rodando ESLint
        run: npm run lint

  test-coverage:
    name: Testes e Cobertura
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalando dependências
        run: npm ci

      - name: Executando testes com cobertura
        run: npm test
