name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Verificação de estilo (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalando dependências
<<<<<<< HEAD
        run: npm install
=======
        run: npm ci
>>>>>>> 7f819beb82c8aba9e2a2b29ac44a18fca99b5690

      - name: Rodando ESLint
        run: npm run lint

<<<<<<< HEAD
  test:
    name: Testes
=======
  test-coverage:
    name: Testes e Cobertura
>>>>>>> 7f819beb82c8aba9e2a2b29ac44a18fca99b5690
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalando dependências
<<<<<<< HEAD
        run: npm install

      - name: Rodando testes
=======
        run: npm ci

      - name: Executando testes com cobertura
>>>>>>> 7f819beb82c8aba9e2a2b29ac44a18fca99b5690
        run: npm test

  docker-build:
    name: Build da imagem Docker (validação)
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Clonando repositório
        uses: actions/checkout@v4

      - name: Buildando imagem
        run: docker build -t app-filmes-pr-test .
